"""ilk_kurulum

Revision ID: a86f84c96217
Revises: 
Create Date: 2026-07-15 20:35:28.059968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a86f84c96217'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('announcement_author_id_fkey'), 'announcement', type_='foreignkey')
    op.create_foreign_key(None, 'announcement', 'user', ['author_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'announcement', type_='foreignkey')
    op.create_foreign_key(op.f('announcement_author_id_fkey'), 'announcement', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###
